"use client";
import {useEffect,useState} from"react";
import{Menu,Search,ShoppingBag,X,ArrowRight,Minus,Plus,Check,ChevronLeft,Coffee,Truck,CreditCard,LayoutDashboard,Package,Tags,Users,Percent,Settings}from"lucide-react";
type Product={id:string;name:string;price:number;notes:string;roast:string;origin:string;altitude:string;process:string;description:string;image:string;image2:string;inventory:number;active:boolean};
type Item={product:Product;size:string;grind:string;subscription:boolean;qty:number};
const P:Product[]=[
{id:"oaxaca",name:"Oaxaca Sierra Norte",price:320,notes:"Chocolate oscuro · Piloncillo · Naranja",roast:"Medio",origin:"Oaxaca, México",altitude:"1,600–1,900 msnm",process:"Lavado",description:"Dulce, profundo y sedoso. Un café de altura que guarda la calidez de la Sierra Norte en cada taza.",image:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1400&q=85",image2:"https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1400&q=85",inventory:42,active:true},
{id:"chiapas",name:"Chiapas Altura",price:295,notes:"Caramelo · Cacao · Frutos rojos",roast:"Medio claro",origin:"Chiapas, México",altitude:"1,400–1,750 msnm",process:"Lavado",description:"Brillante y amable, con dulzor prolongado y una acidez limpia.",image:"https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=1400&q=85",image2:"https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1400&q=85",inventory:31,active:true},
{id:"veracruz",name:"Veracruz Niebla",price:310,notes:"Avellana · Vainilla · Manzana",roast:"Medio",origin:"Veracruz, México",altitude:"1,300–1,650 msnm",process:"Honey",description:"Redondo y aromático, nacido entre neblina y bosque de montaña.",image:"https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=1400&q=85",image2:"https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1400&q=85",inventory:27,active:true},
{id:"guerrero",name:"Guerrero Montaña",price:340,notes:"Chocolate · Ciruela · Miel",roast:"Medio claro",origin:"Guerrero, México",altitude:"1,550–1,850 msnm",process:"Natural",description:"Frutal, envolvente y complejo, cultivado en pequeñas parcelas de montaña.",image:"https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=1400&q=85",image2:"https://images.unsplash.com/photo-1459755486867-b55449bb39ff?auto=format&fit=crop&w=1400&q=85",inventory:19,active:true}];
const mx=(n:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(n);
export default function App(){const[products,setProducts]=useState(P),[view,setView]=useState("home"),[selected,setSelected]=useState<Product|null>(null),[cart,setCart]=useState<Item[]>([]),[drawer,setDrawer]=useState(false),[menu,setMenu]=useState(false);
useEffect(()=>{let s=localStorage.getItem("cbn-products");if(s)setProducts(JSON.parse(s));if(location.pathname.startsWith("/admin"))setView("admin")},[]);
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:"navigate_cafe_demo",title:"Abrir vista de Café Barro Negro",description:"Abre la tienda o el panel administrativo de la demo.",inputSchema:{type:"object",properties:{view:{type:"string",enum:["store","admin"]}},required:["view"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({view:v}:{view:"store"|"admin"})=>{setView(v==="admin"?"admin":"home");history.pushState({},"",v==="admin"?"/admin":"/");return{view:v}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
const save=(x:Product[])=>{setProducts(x);localStorage.setItem("cbn-products",JSON.stringify(x))};const subtotal=cart.reduce((a,x)=>a+x.product.price*x.qty,0);
return <div>{view!=="admin"&&<><Header count={cart.reduce((a,x)=>a+x.qty,0)} cart={()=>setDrawer(true)} home={()=>setView("home")} menu={()=>setMenu(!menu)}/>{menu&&<div className="mobile-menu"><button onClick={()=>setMenu(false)}><X/></button>{["CAFÉ","SUSCRIPCIONES","HISTORIAS","BUSCAR","CUENTA"].map(x=><a href={x==="CAFÉ"?"#coffee":"#"} key={x}>{x}</a>)}</div>}</>}
{view==="home"&&<Home products={products.filter(x=>x.active)} open={p=>{setSelected(p);setView("product");scrollTo(0,0)}} add={p=>{setCart([...cart,{product:p,size:"250 g",grind:"Grano entero",subscription:false,qty:1}]);setDrawer(true)}}/>}
{view==="product"&&selected&&<ProductPage p={products.find(x=>x.id===selected.id)||selected} back={()=>setView("home")} add={x=>{setCart([...cart,x]);setDrawer(true)}}/>}
{view==="checkout"&&<Checkout cart={cart} subtotal={subtotal}/>}
{view==="admin"&&<Admin products={products} save={save} store={()=>{history.pushState({},"","/");setView("home")}}/>}
<Cart open={drawer} close={()=>setDrawer(false)} cart={cart} setCart={setCart} subtotal={subtotal} checkout={()=>{setDrawer(false);setView("checkout");scrollTo(0,0)}}/></div>}
function Header({count,cart,home,menu}:{count:number;cart:()=>void;home:()=>void;menu:()=>void}){return <header className="header"><nav><a href="#coffee">CAFÉ</a><a href="#subscription">SUSCRIPCIONES</a><a href="#stories">HISTORIAS</a></nav><button className="brand" onClick={home}>CAFÉ <b>BARRO NEGRO</b></button><nav><button><Search/> BUSCAR</button><button>CUENTA</button><button onClick={cart}>CARRITO ({count})</button></nav><button className="hamb" onClick={menu}><Menu/></button><button className="bag" onClick={cart}><ShoppingBag/><i>{count}</i></button></header>}
function Home({products,open,add}:{products:Product[];open:(p:Product)=>void;add:(p:Product)=>void}){return <main><section className="hero"><img src="https://images.unsplash.com/photo-1493857671505-72967e2e2760?auto=format&fit=crop&w=2400&q=90" alt="Preparación artesanal de café"/><div className="shade"/><div className="hero-copy"><small>CAFÉ MEXICANO DE ESPECIALIDAD</small><h1>CAFÉ QUE NACE<br/>DE NUESTRA TIERRA.</h1><p>Café mexicano de especialidad, tostado para revelar el carácter de cada origen.</p><a href="#coffee">DESCUBRIR CAFÉ <ArrowRight/></a></div><div className="stamp">OAXACA<br/><b>16°51′N</b></div></section>
<section className="products" id="coffee"><div className="section-title"><h2>CAFÉ PARA<br/>TODOS LOS DÍAS</h2><p>Cuatro orígenes. Cuatro maneras de encontrarte con México.</p></div><div className="grid">{products.map(p=><article className="card" key={p.id}><button className="photo" onClick={()=>open(p)}><img src={p.image}/><img className="hover" src={p.image2}/><i>BARRO<br/>NEGRO</i></button><div><button onClick={()=>open(p)}><h3>{p.name}</h3><p>{p.notes}</p><small>TUESTE {p.roast.toUpperCase()}</small></button><span><b>{mx(p.price)}</b><button onClick={()=>add(p)}>QUICK ADD <Plus/></button></span></div></article>)}</div></section>
<section className="editorial" id="stories"><img src="https://images.unsplash.com/photo-1523742810063-7d00c792326d?auto=format&fit=crop&w=1800&q=85"/><div><small>01 / EL ORIGEN</small><h2>DEL ORIGEN<br/>A TU TAZA.</h2><p>Trabajamos con cafés mexicanos seleccionados por su origen, proceso y carácter.</p><button>CONOCE NUESTRO PROCESO <ArrowRight/></button></div></section>
<section className="story">{[["ORIGEN","Cafés trazables de las montañas de México."],["PRODUCTORES","Relaciones directas y precios que respetan el oficio."],["PROCESO","Cada lote expresa la tierra que lo hizo posible."],["TOSTADO","Perfiles precisos para una taza dulce y limpia."]].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</section>
<section className="subscription" id="subscription"><div><small>SUSCRIPCIÓN BARRO NEGRO</small><h2>NUNCA TE QUEDES<br/>SIN BUEN CAFÉ.</h2></div><div>{["Elige tu café.","Elige la frecuencia.","Nosotros hacemos el resto."].map((x,i)=><p key={x}><b>0{i+1}</b>{x}</p>)}<section>{["Cada 2 semanas","Cada mes","Cada 6 semanas"].map(x=><button key={x}>{x}</button>)}</section><button className="primary">CREAR MI SUSCRIPCIÓN <ArrowRight/></button></div></section><Newsletter/><Footer/></main>}
function ProductPage({p,back,add}:{p:Product;back:()=>void;add:(x:Item)=>void}){const[size,setSize]=useState("250 g"),[grind,setGrind]=useState("Grano entero"),[sub,setSub]=useState(false),[qty,setQty]=useState(1);const factor=size==="500 g"?1.8:size==="1 kg"?3.3:1,total=Math.round(p.price*factor*(sub?.9:1));return <main className="product-page"><button className="back" onClick={back}><ChevronLeft/> TODOS LOS CAFÉS</button><div className="product-image"><img src={p.image}/><i>CAFÉ BARRO NEGRO · MÉXICO</i></div><section className="product-info"><small>CAFÉ BARRO NEGRO</small><h1>{p.name}</h1><strong>{mx(total)}</strong><p className="desc">{p.description}</p><div className="facts">{[["NOTAS DE CATA",p.notes],["ORIGEN",p.origin],["ALTURA",p.altitude],["PROCESO",p.process]].map(x=><div key={x[0]}><small>{x[0]}</small><p>{x[1]}</p></div>)}</div><Choice title="PRESENTACIÓN" values={["250 g","500 g","1 kg"]} value={size} set={setSize}/><Choice title="MOLIENDA" values={["Grano entero","Espresso","V60","Chemex","Prensa francesa","Cafetera"]} value={grind} set={setGrind}/><div className="purchase"><button className={!sub?"active":""} onClick={()=>setSub(false)}>COMPRA ÚNICA <b>{mx(p.price*factor)}</b></button><button className={sub?"active":""} onClick={()=>setSub(true)}>SUSCRÍBETE Y AHORRA 10% <b>{mx(p.price*factor*.9)}</b></button></div><div className="buy"><div><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button>{qty}<button onClick={()=>setQty(qty+1)}><Plus/></button></div><button onClick={()=>add({product:{...p,price:total},size,grind,subscription:sub,qty})}>AGREGAR AL CARRITO — {mx(total*qty)}</button></div></section></main>}
function Choice({title,values,value,set}:{title:string;values:string[];value:string;set:(x:string)=>void}){return <div className="choice"><small>{title}</small><div>{values.map(x=><button className={x===value?"active":""} onClick={()=>set(x)} key={x}>{x}</button>)}</div></div>}
function Cart({open,close,cart,setCart,subtotal,checkout}:{open:boolean;close:()=>void;cart:Item[];setCart:(x:Item[])=>void;subtotal:number;checkout:()=>void}){const q=(i:number,d:number)=>setCart(cart.map((x,j)=>j===i?{...x,qty:Math.max(1,x.qty+d)}:x));return <><div className={"overlay "+(open?"show":"")} onClick={close}/><aside className={"cart "+(open?"open":"")}><header><h2>TU CARRITO</h2><button onClick={close}><X/></button></header>{!cart.length?<div className="empty"><Coffee/><p>Tu carrito espera un buen café.</p></div>:<><div className="lines">{cart.map((x,i)=><article key={i}><img src={x.product.image}/><div><h3>{x.product.name}</h3><p>{x.size}<br/>{x.grind}</p><span><button onClick={()=>q(i,-1)}><Minus/></button>{x.qty}<button onClick={()=>q(i,1)}><Plus/></button></span></div><b>{mx(x.product.price*x.qty)}</b></article>)}</div><div className="free"><i><span style={{width:Math.min(100,subtotal/700*100)+"%"}}/></i><p>{subtotal>=700?"Tu envío es gratis.":`Te faltan ${mx(700-subtotal)} para obtener envío gratis.`}</p></div><footer><p><span>SUBTOTAL</span><b>{mx(subtotal)}</b></p><small>Envío calculado en el checkout</small><button onClick={checkout}>IR AL CHECKOUT <ArrowRight/></button><i>Envíos a todo México.</i></footer></>}</aside></>}
function Checkout({cart,subtotal}:{cart:Item[];subtotal:number}){const[step,setStep]=useState("info"),[loading,setLoading]=useState(false),[ship,setShip]=useState(99);const delay=(next:string)=>{setLoading(true);setTimeout(()=>{setLoading(false);setStep(next)},1000)};if(step==="success")return <Confirm next={()=>setStep("track")}/>;if(step==="track")return <Track/>;return <main className="checkout"><section><button className="check-logo" onClick={()=>location.reload()}>CAFÉ <b>BARRO NEGRO</b></button><div className="demo">SHOPIFY DEMO / SIMULATION MODE</div><div className="crumbs">CARRITO → <b>INFORMACIÓN</b> → ENVÍO → PAGO</div>{loading?<div className="loading"><i/><h2>{step==="info"?"Calculando opciones de envío…":"Procesando pedido…"}</h2></div>:step==="info"?<Info next={()=>delay("shipping")}/>:step==="shipping"?<Shipping value={ship} set={setShip} next={()=>setStep("payment")}/>:<Payment total={subtotal+ship} pay={()=>delay("success")}/>}</section><Summary cart={cart} subtotal={subtotal} ship={step==="info"?null:ship}/></main>}
function Info({next}:{next:()=>void}){return <form className="form" onSubmit={e=>{e.preventDefault();next()}}><h1>INFORMACIÓN DE CONTACTO</h1><label>CORREO ELECTRÓNICO<input required type="email" placeholder="tu@email.com"/></label><div><label>NOMBRE<input required/></label><label>APELLIDOS<input required/></label></div><label>DIRECCIÓN<input required/></label><div><label>COLONIA<input required/></label><label>CÓDIGO POSTAL<input required/></label></div><div><label>CIUDAD<input required/></label><label>ESTADO<select required defaultValue=""><option value="" disabled>Seleccionar</option><option>Ciudad de México</option><option>Oaxaca</option><option>Jalisco</option></select></label></div><label>TELÉFONO<input required/></label><button>CONTINUAR CON EL ENVÍO <ArrowRight/></button></form>}
function Shipping({value,set,next}:{value:number;set:(x:number)=>void;next:()=>void}){return <div className="shipping"><h1>ELIGE TU ENVÍO</h1>{[["ESTAFETA","Estándar · 3–5 días",99],["FEDEX","Express · 1–2 días",179],["DHL","Express · 1–2 días",199]].map(x=><button className={value===x[2]?"active":""} onClick={()=>set(+x[2])} key={x[0]}><i/><span><b>{x[0]}</b><small>{x[1]}</small></span><strong>{mx(+x[2])}</strong></button>)}<p><Truck/> Envíos gestionados con Envia.com</p><button className="continue" onClick={next}>CONTINUAR AL PAGO <ArrowRight/></button></div>}
function Payment({total,pay}:{total:number;pay:()=>void}){return <form className="form" onSubmit={e=>{e.preventDefault();pay()}}><h1>PAGO</h1><p className="safe"><CreditCard/> Tarjeta · Datos ficticios, sin cargos reales</p><label>NÚMERO DE TARJETA<input required placeholder="4242 4242 4242 4242"/></label><div><label>MM/AA<input required placeholder="12/28"/></label><label>CVV<input required placeholder="123"/></label></div><button>PAGAR {mx(total)} <ArrowRight/></button><small>Esta simulación no almacena información de tarjetas.</small></form>}
function Summary({cart,subtotal,ship}:{cart:Item[];subtotal:number;ship:number|null}){return <aside className="summary"><h2>RESUMEN</h2>{cart.map((x,i)=><div key={i}><img src={x.product.image}/><span><b>{x.product.name}</b><small>{x.size} · {x.grind}</small></span><strong>{mx(x.product.price*x.qty)}</strong></div>)}<footer><p>Subtotal <b>{mx(subtotal)}</b></p><p>Envío <b>{ship===null?"Por calcular":mx(ship)}</b></p><p>TOTAL <b>{mx(subtotal+(ship||0))}</b></p></footer></aside>}
function Confirm({next}:{next:()=>void}){return <main className="confirm"><i><Check/></i><small>PEDIDO #BN-1048</small><h1>GRACIAS POR<br/>TU COMPRA</h1><p>Tu café está en camino.<br/>Te enviaremos las actualizaciones de tu pedido por correo electrónico.</p><button onClick={next}>VER MI PEDIDO <ArrowRight/></button></main>}
function Track(){return <main className="track"><small>PEDIDO CONFIRMADO</small><h1>#BN-1048</h1><h2>PREPARANDO PEDIDO</h2><section>{["Pedido confirmado","Preparando paquete","En tránsito","Entregado"].map((x,i)=><p className={i===0?"done":""} key={x}><i/>{x}{i===0&&<small>15 septiembre · 20:48</small>}</p>)}</section><aside><p>PAQUETERÍA <b>ESTAFETA</b></p><p>NÚMERO DE GUÍA <b>BN239485MX</b></p><button>RASTREAR PEDIDO <ArrowRight/></button></aside><div className="demo">INFORMACIÓN SIMULADA</div></main>}
function Admin({products,save,store}:{products:Product[];save:(x:Product[])=>void;store:()=>void}){const[tab,setTab]=useState("Resumen"),[edit,setEdit]=useState<Product|null>(null),[order,setOrder]=useState(false),[guide,setGuide]=useState("GENERAR GUÍA");const nav:any[]=[["Resumen",LayoutDashboard],["Pedidos",Package],["Productos",Tags],["Clientes",Users],["Envíos",Truck],["Descuentos",Percent],["Configuración",Settings]];return <main className="admin"><aside><h2>CAFÉ <b>BARRO NEGRO</b><small>ADMIN / DEMO</small></h2><nav>{nav.map(([n,I])=><button className={tab===n?"active":""} onClick={()=>setTab(n)} key={n}><I/>{n.toUpperCase()}</button>)}</nav><button onClick={store}>VER TIENDA <ArrowRight/></button></aside><section className="admin-main"><header><div><small>PANEL DE CONTROL</small><h1>{tab.toUpperCase()}</h1></div><span>15 SEP 2026</span></header>{tab==="Resumen"?<Dashboard orders={()=>setTab("Pedidos")}/>:tab==="Pedidos"?<Orders open={order} setOpen={setOrder} guide={guide} generate={()=>{setGuide("CONECTANDO CON ENVIA.COM…");setTimeout(()=>setGuide("✓ GUÍA GENERADA"),1100)}}/>:tab==="Productos"?<Products data={products} edit={setEdit} toggle={id=>save(products.map(p=>p.id===id?{...p,active:!p.active}:p))} remove={id=>save(products.filter(p=>p.id!==id))}/>:<div className="placeholder"><Coffee/><h2>{tab}</h2><p>Vista preparada para la siguiente etapa de la demo.</p></div>}</section>{edit&&<Editor p={edit} close={()=>setEdit(null)} save={p=>{save(products.map(x=>x.id===p.id?p:x));setEdit(null)}}/>}</main>}
function Dashboard({orders}:{orders:()=>void}){return <><div className="metrics">{[["VENTAS HOY","$8,420","+18%"],["PEDIDOS","24","+6"],["TICKET PROMEDIO","$351","+4%"],["CONVERSIÓN","3.8%","+0.7"]].map(x=><article key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><i>{x[2]}</i></article>)}</div><div className="chart"><header><small>VENTAS · ÚLTIMOS 7 DÍAS</small><h2>$42,860 MXN</h2></header><section>{[48,70,55,86,64,95,78].map((h,i)=><i key={i} style={{height:h+"%"}}><span>{"LMMJVSD"[i]}</span></i>)}</section></div><button className="recent" onClick={orders}><span><b>PEDIDOS RECIENTES</b><small>Mariana López · #BN-1048</small></span><strong>$419</strong><ArrowRight/></button></>}
function Orders({open,setOpen,guide,generate}:{open:boolean;setOpen:(x:boolean)=>void;guide:string;generate:()=>void}){if(open)return <div className="order-detail"><button onClick={()=>setOpen(false)}><ChevronLeft/> PEDIDOS</button><header><div><small>PEDIDO</small><h2>#BN-1048</h2></div><span>PAGADO</span></header><section>{[["CLIENTE","Mariana López\nmariana@ejemplo.mx\n55 1234 5678","DIRECCIÓN","Ámsterdam 128, Hipódromo\n06100, Ciudad de México"],["PRODUCTOS","Oaxaca Sierra Norte\n250 g · Grano entero","PAGO DEMO","•••• 4242 · $419 MXN"],["ENVÍO","ESTAFETA · Estándar\nGuía: "+(guide.includes("✓")?"BN239485MX":"Pendiente"),"",""]].map((x,i)=><article key={i}><h3>{x[0]}</h3><p>{x[1]}</p><h3>{x[2]}</h3><p>{x[3]}</p>{i===2&&<button onClick={generate}>{guide}</button>}</article>)}</section></div>;return <div className="orders">{[["#BN-1048","Mariana López","$419","Pagado","Preparando"],["#BN-1047","Carlos Méndez","$699","Pagado","Enviado"]].map(x=><button onClick={()=>setOpen(true)} key={x[0]}>{x.map(v=><span key={v}>{v}</span>)}<ArrowRight/></button>)}</div>}
function Products({data,edit,toggle,remove}:{data:Product[];edit:(p:Product)=>void;toggle:(id:string)=>void;remove:(id:string)=>void}){return <div className="admin-products"><button className="new">+ CREAR PRODUCTO</button>{data.map(p=><article key={p.id}><img src={p.image}/><div><h3>{p.name}</h3><p>{p.inventory} unidades · {mx(p.price)}</p></div><i className={p.active?"on":""}>{p.active?"ACTIVO":"OCULTO"}</i><button onClick={()=>toggle(p.id)}>{p.active?"DESACTIVAR":"ACTIVAR"}</button><button onClick={()=>edit(p)}>EDITAR</button><button onClick={()=>remove(p.id)}>ELIMINAR</button></article>)}</div>}
function Editor({p:base,close,save}:{p:Product;close:()=>void;save:(p:Product)=>void}){const[p,setP]=useState(base);return <div className="editor-bg"><form className="editor" onSubmit={e=>{e.preventDefault();save(p)}}><header><h2>EDITAR PRODUCTO</h2><button type="button" onClick={close}><X/></button></header><label>NOMBRE<input value={p.name} onChange={e=>setP({...p,name:e.target.value})}/></label><div><label>PRECIO<input type="number" value={p.price} onChange={e=>setP({...p,price:+e.target.value})}/></label><label>INVENTARIO<input type="number" value={p.inventory} onChange={e=>setP({...p,inventory:+e.target.value})}/></label></div><label>FOTOGRAFÍA (URL)<input value={p.image} onChange={e=>setP({...p,image:e.target.value})}/></label><label>DESCRIPCIÓN<textarea value={p.description} onChange={e=>setP({...p,description:e.target.value})}/></label><label>NOTAS DE CATA<input value={p.notes} onChange={e=>setP({...p,notes:e.target.value})}/></label><button>GUARDAR CAMBIOS</button></form></div>}
function Newsletter(){return <section className="newsletter"><h2>CAFÉ, HISTORIAS<br/>Y NUEVOS ORÍGENES.</h2><form><input type="email" placeholder="tu@email.com"/><button>SUSCRIBIRME <ArrowRight/></button></form></section>}
function Footer(){return <footer className="footer"><h2>CAFÉ<br/><b>BARRO NEGRO</b></h2>{[["CAFÉ","Todos los cafés","Suscripciones","Equipo"],["NOSOTROS","Nuestra historia","Productores","Contacto"],["AYUDA","Envíos","Preguntas frecuentes","Cambios y devoluciones"],["SÍGUENOS","Instagram","TikTok"]].map(g=><div key={g[0]}><b>{g[0]}</b>{g.slice(1).map(x=><a href="#" key={x}>{x}</a>)}</div>)}<p>MÉXICO © 2026 CAFÉ BARRO NEGRO</p></footer>}
